In [1]:
import numpy as np

# Numpy is used for fast vector operations

In [2]:
normal_list = [1, 2, 3]
numpy_array = np.array(normal_list)

# Let's try to compare both for large arrays!

In [35]:
normal_list = lisvt(range(1,10000000))
numpy_array = np.array(normal_list)

# print("Normal array: {} \nType: {} \n\n -------- \n\nNumpy array: {} \nType: {}".format(normal_list, type(normal_list), numpy_array, type(numpy_array)))

# How to subtract 1 from each element?

In [36]:
%%time

# List compreshension method
print("List compreshenison method: ")
a = [x - 1 for x in normal_list] 

List compreshenison method: 
CPU times: user 14.6 s, sys: 15.9 s, total: 30.5 s
Wall time: 8min 32s


In [37]:
%%time

# Loop method
print("Loop method: ")

a = []
for x in normal_list:
    a.append(x-1)

Loop method: 
CPU times: user 21 s, sys: 11 s, total: 32 s
Wall time: 8min 31s


In [38]:
%%time

# Numpy
print("Numpy method: ")

a = numpy_array - 1

Numpy method: 
CPU times: user 1.37 s, sys: 3.13 s, total: 4.49 s
Wall time: 1min 47s


# Numpy is fast and easy!

In [12]:
a = np.array([4, 5, 7, 89, 343, 767, 23])

In [14]:
print("numpy array a: {}\ntype of a: {}\n".format(a, type(a)))

print("What is the 4th element? : {}".format(a[3]))
print("What is the first element? : {}".format(a[0]))
print("What is the last element? : {}".format(a[-1]))
print("What is the second last element? : {}".format(a[-2]))

numpy array a: [  4   5   7  89 343 767  23]
type of a: <class 'numpy.ndarray'>

What is the 4th element? : 89
What is the first element? : 4
What is the last element? : 23
What is the second last element? : 767


# Finding the shape of the array

In [45]:
a = np.array([[3, 4],
              [5, 7],
              [9, 77]])

print("array a:\n {}\narray shape: {}".format(a,
                                              a.shape))

rows, cols = a.shape

print("Rows: {}\nColumns: {}".format(rows, cols))

array a:
 [[ 3  4]
 [ 5  7]
 [ 9 77]]
array shape: (3, 2)
Rows: 3
Columns: 2


# Handy numpy functions

In [5]:
a = np.zeros((4,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
a = np.ones((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
a = np.full((3,3), 555)
a

array([[555, 555, 555],
       [555, 555, 555],
       [555, 555, 555]])

In [17]:
a = np.random.randint(1, 30, size=(4, 8))
a

array([[22,  5, 20, 26, 23, 25,  6,  3],
       [12,  4, 20, 10, 28, 18, 21, 13],
       [19,  4,  1,  5, 11, 29,  9, 29],
       [ 3, 17, 13, 20, 25, 15, 19, 26]])

In [18]:
a = np.random.random((5,5))
a

array([[0.0735311 , 0.54719671, 0.40940399, 0.71902975, 0.5539599 ],
       [0.87589601, 0.22286364, 0.28840412, 0.6714646 , 0.49373039],
       [0.6887555 , 0.5340898 , 0.68114597, 0.95924657, 0.3645496 ],
       [0.30846282, 0.85385316, 0.73063915, 0.14620541, 0.45924258],
       [0.28967141, 0.09916125, 0.39629238, 0.33648872, 0.04158296]])

# Array Indexing

In [19]:
a = np.random.randint(4, 99, size=(8,8))
a

array([[46, 69, 44, 45, 31, 90, 33,  7],
       [65, 37, 39, 55, 98, 54, 46, 81],
       [89, 25, 63, 48, 59, 90, 91, 83],
       [36, 67, 40, 63, 54, 21, 71, 74],
       [86, 90, 21, 68, 45, 95, 85, 36],
       [61, 64, 29,  4, 65, 15, 88, 30],
       [12, 20,  7, 72, 71, 12, 75,  6],
       [48, 38, 12, 78, 32,  4,  7, 63]])

In [28]:
print("First row: {}".format(a[0]))
print("Second row: {}".format(a[1]))

print("Last row: {}".format(a[-1]))
print("Second Last row: {}".format(a[-2]))

First row: [46 69 44 45 31 90 33  7]
Second row: [65 37 39 55 98 54 46 81]
Last row: [48 38 12 78 32  4  7 63]
Second Last row: [12 20  7 72 71 12 75  6]


In [33]:
print("First 3 rows:\n {}".format(a[:3]))
print("First 3 rows:\n {}".format(a[:3, :]))

First 3 rows:
 [[46 69 44 45 31 90 33  7]
 [65 37 39 55 98 54 46 81]
 [89 25 63 48 59 90 91 83]]
First 3 rows:
 [[46 69 44 45 31 90 33  7]
 [65 37 39 55 98 54 46 81]
 [89 25 63 48 59 90 91 83]]


In [32]:
print("First 3 columns:\n {}".format(a[:, :3]))

First 3 columns:
 [[46 69 44]
 [65 37 39]
 [89 25 63]
 [36 67 40]
 [86 90 21]
 [61 64 29]
 [12 20  7]
 [48 38 12]]


In [24]:
print("First 3 rows and 2 columns:\n {}".format(a[:3,:2]))

First 3 rows and 2 columns:
 [[46 69]
 [65 37]
 [89 25]]


In [36]:
print("Last 3 rows and last 2 columns:\n {}".format(a[-3:,-2:]))

Last 3 rows and last 2 columns:
 [[88 30]
 [75  6]
 [ 7 63]]


In [35]:
print("From 2nd row to 4th row and 2nd column to 5th column:\n {}".format(a[1:5,1:6]))

From 2nd row to 4th row and 2nd column to 5th column:
 [[37 39 55 98 54]
 [25 63 48 59 90]
 [67 40 63 54 21]
 [90 21 68 45 95]]


## Easy to remember

- [row_start:row_end, col_start:col_end]
- "-" sign means from end
- keeping it empty (no number) means till the end
- upper boundary number is one extra than required

### Boolean: Get all elements greater than x

In [40]:
x = 50

b = a > x
b

array([[False,  True, False, False, False,  True, False, False],
       [ True, False, False,  True,  True,  True, False,  True],
       [ True, False,  True, False,  True,  True,  True,  True],
       [False,  True, False,  True,  True, False,  True,  True],
       [ True,  True, False,  True, False,  True,  True, False],
       [ True,  True, False, False,  True, False,  True, False],
       [False, False, False,  True,  True, False,  True, False],
       [False, False, False,  True, False, False, False,  True]])

In [41]:
a[b]

array([69, 90, 65, 55, 98, 54, 81, 89, 63, 59, 90, 91, 83, 67, 63, 54, 71,
       74, 86, 90, 68, 95, 85, 61, 64, 65, 88, 72, 71, 75, 78, 63])

In [42]:
a[a>x]

array([69, 90, 65, 55, 98, 54, 81, 89, 63, 59, 90, 91, 83, 67, 63, 54, 71,
       74, 86, 90, 68, 95, 85, 61, 64, 65, 88, 72, 71, 75, 78, 63])

In [45]:
a==90

array([[False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [47]:
a[a%2==0]

array([46, 44, 90, 98, 54, 46, 48, 90, 36, 40, 54, 74, 86, 90, 68, 36, 64,
        4, 88, 30, 12, 20, 72, 12,  6, 48, 38, 12, 78, 32,  4])